entities:
  accesskey:
    aliases:
    - ak
    columns:
    - title: ID
      content: AccessKeyId
    - title: Tag
      content: Tag
    - title: State
      content: State
    - title: ExpirationDate
      content: ExpirationDate
  apiaccessrule:
    columns:
    - title: ID
      content: ApiAccessRuleId
    - title: Description
      content: Description
    - title: CA
      content: CaIds
    - title: CN
      content: Cns
    - title: IP Ranges
      content: IpRanges
  apilog:
    aliases:
    - log
    columns:
    - title: Date
      content: QueryDate
    - title: UserAgent
      content: QueryUserAgent
    - title: Call
      content: QueryCallName
    - title: Payload
      content: QueryPayloadRaw
    - title: Status
      content: ResponseStatusCode
  catalog:
    explode: true
    sort: true
    columns:
    - title: Service
      content: "map(Entries, #?.Service)"
    - title: Category
      content: "map(Entries, #?.Category)"
    - title: Title
      content: "map(Entries, #?.Title)"
    - title: UnitPrice
      content: "map(Entries, #?.UnitPrice)"
    - title: Flags
      content: "map(Entries, #?.Flags)"
  consumptionaccount:
    aliases:
    - consumption
    columns:
    - title: From
      content: FromDate
    - title: To
      content: ToDate
    - title: Account
      content: AccountId
    - title: Category
      content: Category
    - title: Service
      content: Service
    - title: Subregion
      content: SubregionName
    - title: Operation
      content: Operation
    - title: Value
      content: Value
    - title: Unit Price
      content: UnitPrice
    - title: Price
      content: Price
  exporttask:
    primary: ExportTaskId
  flexiblegpu:
    aliases:
    - fgpu
  flexiblegpucatalog:
    no_aliases: true
    columns:
    - title: Name
      content: ModelName
    - title: VRAM
      content: VRam
    - title: Max CPu
      content: MaxCpu
    - title: Max RAM
      content: MaxRam
    - title: Generations
      content: Generations
  imageexporttask:
    primary: TaskId
  listenerrule:
    primary: ListenerRuleName
  loadbalancer:
    aliases:
    - lb
    - lbu
  loadbalancertag:
    columns:
    - title: LBU
      content: LoadBalancerName
    - title: Key
      content: Key
    - title: Value
      content: Value
  location:
    columns:
    - title: Code
      content: Code
    - title: Name
      content: Name
  natservice:
    aliases:
    - nat
    columns:
    - title: ID
      content: NatServiceId
    - title: Name
      content: "find(Tags, #?.Key == \"Name\")?.Value"
    - title: State
      content: State
    - title: PublicIp
      content: "map(PublicIps, #?.PublicIp)"
    - title: NetId
      content: NetId
    - title: SubnetId
      content: SubnetId
  netaccesspointservice:
    no_aliases: true
    columns:
    - title: ID
      content: ServiceId
    - title: Name
      content: ServiceName
    - title: IP Ranges
      content: IpRanges
  policy:
    no_aliases: true
    columns:
    - title: ORN
      content: Orn
    - title: Name
      content: PolicyName
    - title: Default Version
      content: PolicyDefaultVersionId
    - title: Resources Count
      content: ResourcesCount
    primary: PolicyOrn
  policyversion:
    no_aliases: true
    columns:
    - title: Version
      content: VersionId
    - title: Default
      content: DefaultVersion
    - title: Date
      content: CreationDate
    primary: PolicyOrn
  quota:
    explode: true
    columns:
    - title: Type
      content: QuotaType
    - title: Collection
      content: "map(Quotas, #?.QuotaCollection)"
    - title: Name
      content: "map(Quotas, #?.Name)"
    - title: Used
      content: "map(Quotas, #?.UsedValue)"
    - title: Max
      content: "map(Quotas, #?.MaxValue)"
    - title: Description
      content: "map(Quotas, #?.Description)"
    primary: QuotaName
  snapshot:
    aliases:
    - snap
    columns:
    - title: ID
      content: SnapshotId
    - title: Name
      content: "find(Tags, #?.Key == \"Name\")?.Value"
    - title: State
      content: State
    - title: Volume
      content: VolumeId
    - title: Size
      content: VolumeSize
    - title: CreationDate
      content: CreationDate
  snapshotexporttask:
    primary: TaskId
  tag:
    columns:
    - title: Resource
      content: ResourceId
    - title: Type
      content: ResourceType
    - title: Key
      content: Key
    - title: Value
      content: Value
  user:
    columns:
    - title: Name
      content: UserName
    - title: Email
      content: UserEmail
    primary: UserName
  usergroup:
    primary: UserGroupName
  vmshealth:
    columns:
    - title: VM
      content: VmId
    - title: State
      content: State
  vmsstate:
    columns:
    - title: VM ID
      content: VmId
    - title: SubregionName
      content: SubregionName
    - title: State
      content: VmState
  volume:
    aliases:
    - vol
    columns:
    - title: ID
      content: VolumeId
    - title: Name
      content: "find(Tags, #?.Key == \"Name\")?.Value"
    - title: Type
      content: VolumeType
    - title: State
      content: State
    - title: Size
      content: Size
    - title: Iops
      content: Iops
    - title: VM
      content: "map(LinkedVolumes, #?.VmId)"
    - title: Device
      content: "map(LinkedVolumes, #?.DeviceName)"
  volumeupdatetask:
    primary: TaskId
aliases:
- entity: flexiblegpu
  group: flexiblegpu
  use: catalog
  short: alias for api ReadFlexibleGpuCatalog
  command:
  - api
  - ReadFlexibleGpuCatalog
  - --output
  - table
- entity: flexiblegpu
  group: flexiblegpu
  use: link fgpu_id vm_id
  short: alias for api LinkFlexibleGpu --FlexibleGpuId fgpu_id --VmId vm_id
  command:
  - api
  - LinkFlexibleGpu
  - --FlexibleGpuId
  - '%0'
  - --VmId
  - '%1'
  - --output
  - success
- entity: flexiblegpu
  group: flexiblegpu
  use: unlink fgpu_id
  short: alias for api UnlinkFlexibleGpu --FlexibleGpuId fgpu_id
  command:
  - api
  - UnlinkFlexibleGpu
  - --FlexibleGpuId
  - '%0'
  - --output
  - success
- entity: internetservice
  group: internetservice
  use: link service_id net_id
  short: alias for api LinkInternetService --InternetServiceId service_id --NetId net_id
  command:
  - api
  - LinkInternetService
  - --InternetServiceId
  - '%0'
  - --NetId
  - '%1'
  - --output
  - success
- entity: internetservice
  group: internetservice
  use: unlink service_id net_id
  short: alias for api UnlinkInternetService --InternetServiceId service_id --NetId net_id
  command:
  - api
  - UnlinkInternetService
  - --InternetServiceId
  - '%0'
  - --NetId
  - '%1'
  - --output
  - success
- entity: nic
  group: nic
  use: link nic_id vm_id
  short: alias for api LinkNic --NicId nic_id --VmId vm_id
  command:
  - api
  - LinkNic
  - --NicId
  - '%0'
  - --VmId
  - '%1'
  - --output
  - yaml
  flags:
  - name: device_number
    alias_to: DeviceNumber
    required: true
- entity: netaccesspoint
  group: netaccesspoint
  use: services
  short: alias for api ReadNetAccessPointServices
  command:
  - api
  - ReadNetAccessPointServices
  - --output
  - table
- entity: netpeering
  group: netpeering
  use: accept netpeering_id
  short: alias for api AcceptNetPeering --NetPeeringId netpeering_id
  command:
  - api
  - AcceptNetPeering
  - --NetPeeringId
  - '%0'
  - --output
  - success
- entity: netpeering
  group: netpeering
  use: reject netpeering_id
  short: alias for api RejectNetPeering --NetPeeringId netpeering_id
  command:
  - api
  - RejectNetPeering
  - --NetPeeringId
  - '%0'
  - --output
  - success
- entity: policy
  group: policy
  use: list
  aliases:
  - ls
  short: alias for api ReadPolicies
  command:
  - api
  - ReadPolicies
  - --output
  - table
  flags:
  - name: only-linked
    alias_to: Filters.OnlyLinked
  - name: path-prefix
    alias_to: Filters.PathPrefix
  - name: scope
    alias_to: Filters.Scope
  - name: first-item
    alias_to: FirstItem
- entity: policy
  group: policy
  use: describe policy_orn
  aliases:
  - desc
  short: alias for api ReadPolicy --PolicyOrn policy_orn
  command:
  - api
  - ReadPolicy
  - --PolicyOrn
  - '%0'
  - --output
  - yaml
- entity: policy
  group: policy
  use: create
  short: alias for api CreatePolicy
  command:
  - api
  - CreatePolicy
  - --output
  - yaml
  flags:
  - name: description
    alias_to: Description
  - name: document
    alias_to: Document
    required: true
    type: file
    usage: The file storing the policy document, corresponding to a JSON string that contains the policy.
  - name: path
    alias_to: Path
  - name: name
    alias_to: PolicyName
    required: true
- entity: policy
  group: policy
  use: delete policy_orn
  aliases:
  - del
  short: alias for api DeletePolicy --PolicyOrn policy_orn
  command:
  - api
  - DeletePolicy
  - --PolicyOrn
  - '%0'
  - --output
  - none
  prompt:
    action: delete
    display:
    - api
    - ReadPolicy
    - --PolicyOrn
    - '%0'
    - --output
    - table
- entity: policy
  group: policy
  use: link policy_orn user_name
  short: alias for api LinkPolicy --PolicyOrn policy_orn --UserName user_name
  command:
  - api
  - LinkPolicy
  - --PolicyOrn
  - '%0'
  - --UserName
  - '%1'
  - --output
  - success
- entity: policy
  group: policy
  use: unlink policy_orn user_name
  short: alias for api UnlinkPolicy --PolicyOrn policy_orn --UserName user_name
  command:
  - api
  - UnlinkPolicy
  - --PolicyOrn
  - '%0'
  - --UserName
  - '%1'
  - --output
  - success
- entity: policyversion
  group: policyversion
  use: list policy_orn
  aliases:
  - ls
  short: alias for api ReadPolicyVersions --PolicyOrn policy_orn
  command:
  - api
  - ReadPolicyVersions
  - --PolicyOrn
  - '%0'
  - --output
  - table
- entity: policyversion
  group: policyversion
  use: describe policy_orn version
  aliases:
  - desc
  short: alias for api ReadPolicyVersion --PolicyOrn policy_orn --VersionId version
  command:
  - api
  - ReadPolicyVersion
  - --PolicyOrn
  - '%0'
  - --VersionId
  - '%1'
  - --output
  - yaml
- entity: policyversion
  group: policyversion
  use: create policy_orn
  short: alias for api CreatePolicyVersion --PolicyOrn policy_orn
  command:
  - api
  - CreatePolicyVersion
  - --PolicyOrn
  - '%0'
  - --output
  - yaml
  flags:
  - name: document
    alias_to: Document
    required: true
    type: file
    usage: The file storing the policy document, corresponding to a JSON string that contains the policy.
  - name: default
    alias_to: SetAsDefault
- entity: policyversion
  group: policyversion
  use: delete policy_orn version
  aliases:
  - del
  short: alias for api DeletePolicyVersion --PolicyOrn policy_orn --VersionId version
  command:
  - api
  - DeletePolicyVersion
  - --PolicyOrn
  - '%0'
  - --VersionId
  - '%1'
  - --output
  - none
  prompt:
    action: delete
    display:
    - api
    - ReadPolicyVersion
    - --PolicyOrn
    - '%0'
    - --VersionId
    - '%1'
    - --output
    - table
- entity: policyversion
  group: policyversion
  use: set-default policy_orn version
  aliases:
  - default
  short: alias for api SetDefaultPolicyVersion --PolicyOrn policy_orn --VersionId version
  command:
  - api
  - SetDefaultPolicyVersion
  - --PolicyOrn
  - '%0'
  - --VersionId
  - '%1'
  - --output
  - success
- entity: volume
  group: volume
  use: link volume_id vm_id
  short: alias for api LinkVolume --VolumeId volume_id --VmId vm_id
  command:
  - api
  - LinkVolume
  - --VolumeId
  - '%0'
  - --VmId
  - '%1'
  - --output
  - success
  flags:
  - name: device_name
    alias_to: DeviceName
    required: true
- entity: volume
  group: volume
  use: unlink volume_id
  short: alias for api UnlinkVolume --VolumeId link_volume_id
  command:
  - api
  - UnlinkVolume
  - --VolumeId
  - '%0'
  - --output
  - success
  flags:
  - name: force
    alias_to: ForceUnlink
- entity: vm
  group: vm
  use: start vm_id [vm_id]...
  short: alias for api StartVms --VmIds vm_id
  command:
  - api
  - StartVms
  - --VmIds
  - '%*'
  - --output
  - table
- entity: vm
  group: vm
  use: stop vm_id [vm_id]...
  short: alias for api StopVms --VmIds vm_id
  command:
  - api
  - StopVms
  - --VmIds
  - '%*'
  - --output
  - table
- entity: vm
  group: vm
  use: readconsole vm_id
  short: alias for api ReadConsoleOutput --VmId vm_id
  command:
  - api
  - ReadConsoleOutput
  - --VmId
  - '%0'
  - --jq
  - .ConsoleOutput
  - --output
  - base64
