contents:
  ListBuckets:
    content: Buckets
    entity: bucket
    group: Bucket
  ListObjectsV2:
    content: Contents
    entity: object
    group: Object
  ListObjectVersions:
    content: Versions
    entity: objectversion
    group: Object
  GetObject:
    entity: objectmetadata
    group: Object
entities:
  bucket:
    columns:
    - title: Name
      content: .Name
    primary: Bucket
  object:
    columns:
    - title: Key
      content: .Key
    - title: Size
      content: .Size
    - title: LastModified
      content: .LastModified
    primary: Key
aliases:
- entity: object
  use: describe key
  alias_to: GetObject
  aliases:
  - desc
  short: Display an object metadata, alias for api GetObject --Key key
  command:
  - api
  - GetObject
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: download key
  alias_to: GetObject
  aliases:
  - down
  short: Download an object to the standard output, alias for api GetObject --Key key
  command:
  - api
  - GetObject
  - --Key
  - '%0'
  - --output
  - body
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: bucket
  sub_command: versioning
  use: describe bucket
  alias_to: GetBucketVersioning
  aliases:
  - desc
  short: Display versioning configuration, alias for api GetBucketVersioning --Bucket bucket
  command:
  - api
  - GetBucketVersioning
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: versioning
  use: enable bucket
  alias_to: PutBucketVersioning
  short: Enable versioning, alias for api PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Enabled
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Enabled
  - --output
  - success
- entity: bucket
  sub_command: versioning
  use: disable bucket
  alias_to: PutBucketVersioning
  short: Disable versioning, alias for api PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Suspended
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Suspended
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: describe bucket
  alias_to: GetBucketEncryption
  aliases:
  - desc
  short: Display encryption configuration, alias for api GetBucketEncryption --Bucket bucket
  command:
  - api
  - GetBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: encryption
  use: enable bucket
  alias_to: PutBucketEncryption
  short: Enable encryption, alias for api PutBucketEncryption --Bucket bucket --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm AES256
  command:
  - api
  - PutBucketEncryption
  - --Bucket
  - '%0'
  - --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm
  - AES256
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: disable bucket
  alias_to: DeleteBucketEncryption
  short: Disable encryption, alias for api DeleteBucketEncryption --Bucket bucket
  command:
  - api
  - DeleteBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - success
