contents:
  ListBuckets:
    content: Buckets
    entity: bucket
    group: Bucket
  HeadBucket:
    content: .
    entity: bucket
    group: Bucket
  ListObjectsV2:
    content: Contents
    entity: object
    group: Object
  ListObjectVersions:
    content: Versions
    entity: objectversion
    group: Object
  GetObject:
    content: .
    entity: objectmetadata
    group: Object
  HeadObject:
    content: .
    entity: objectmetadata
    group: Object
  GetBucketAcl:
    content: .
    entity: acl
    group: Bucket
  GetBucketCors:
    content: CORSRules
    entity: cors
    group: Bucket
  GetBucketEncryption:
    content: ServerSideEncryptionConfiguration
    entity: encryption
    group: Bucket
  GetBucketVersioning:
    entity: versioning
    group: Bucket
  GetBucketLocation:
    content: .
    entity: location
    group: Bucket
  GetBucketPolicy:
    content: Policy
    entity: policy
    group: Bucket
  GetBucketLifecycleConfiguration:
    content: .
    entity: lifecycle
    group: Bucket
  GetBucketWebsite:
    content: .
    entity: website
    group: Bucket
  PutBucketWebsite:
    content: .
    entity: website
    group: Bucket
  GetObjectAcl:
    content: .
    entity: acl
    group: Object
  GetObjectRetention:
    content: Retention
    entity: retention
    group: Object
  GetObjectLockConfiguration:
    content: ObjectLockConfiguration
    entity: lockconfiguration
    group: Object
  GetObjectTagging:
    content: .
    entity: tagging
    group: Object
entities:
  bucket:
    columns:
    - title: Name
      content: .Name
    primary: Bucket
  object:
    columns:
    - title: Key
      content: .Key
    - title: Size
      content: .Size
    - title: LastModified
      content: .LastModified
    primary: Key
  acl:
    no_aliases: true
  cors:
    no_aliases: true
  encryption:
    no_aliases: true
  versioning:
    no_aliases: true
  location:
    no_aliases: true
  policy:
    no_aliases: true
  lifecycle:
    no_aliases: true
  website:
    no_aliases: true
  objectversion:
    no_aliases: true
  objectmetadata:
    no_aliases: true
  retention:
    no_aliases: true
  lockconfiguration:
    no_aliases: true
  tagging:
    no_aliases: true
aliases:
- entity: bucket
  use: describe bucket
  alias_to: HeadBucket
  aliases:
  - desc
  short: Display a bucket, alias for api HeadBucket --Bucket bucket
  command:
  - api
  - HeadBucket
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: object
  use: describe key
  alias_to: HeadObject
  aliases:
  - desc
  short: Display an object metadata, alias for api HeadObject --Key key
  command:
  - api
  - HeadObject
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: versions
  alias_to: ListObjectVersions
  aliases:
  - desc
  short: Display an object metadata, alias for api ListObjectVersions
  command:
  - api
  - ListObjectVersions
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: download key
  alias_to: GetObject
  aliases:
  - down
  short: Download an object to the standard output, alias for api GetObject --Key key
  command:
  - api
  - GetObject
  - --Key
  - '%0'
  - --output
  - body
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  use: copy bucket_src/key_src key_dst
  alias_to: CopyObject
  aliases:
  - cp
  short: Copy an object, alias for api CopyObject --CopySource bucket_src/key_src --Key key_dst
  command:
  - api
  - CopyObject
  - --CopySource
  - '%0'
  - --Key
  - '%1'
  - --output
  - success
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
  - name: expires
    alias_to: Expires
  - name: grant-full-control
    alias_to: GrantFullControl
  - name: grant-read
    alias_to: GrantRead
  - name: grant-read-acp
    alias_to: GrantReadACP
  - name: grant-write-acp
    alias_to: GrantWriteACP
  - name: tagging
    alias_to: Tagging
  - name: tagging-directive
    alias_to: TaggingDirective
  - name: cache-control
    alias_to: CacheControl
  - name: content-disposition
    alias_to: ContentDisposition
  - name: content-encoding
    alias_to: ContentEncoding
  - name: content-language
    alias_to: ContentLanguage
  - name: content-length
    alias_to: ContentLength
  - name: content-type
    alias_to: ContentType
  - name: server-side-encryption
    alias_to: ServerSideEncryption
  - name: object-lock-mode
    alias_to: ObjectLockMode
  - name: object-lock-retain-until-date
    alias_to: ObjectLockRetainUntilDate
  - name: website-redirect-location
    alias_to: WebsiteRedirectLocation
- entity: bucket
  sub_command: versioning
  use: describe bucket
  alias_to: GetBucketVersioning
  aliases:
  - desc
  short: Display versioning configuration, alias for api GetBucketVersioning --Bucket bucket
  command:
  - api
  - GetBucketVersioning
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: versioning
  use: enable bucket
  alias_to: PutBucketVersioning
  short: Enable versioning, alias for api PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Enabled
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Enabled
  - --output
  - success
- entity: bucket
  sub_command: versioning
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: PutBucketVersioning
  short: Disable versioning, alias for api PutBucketVersioning --Bucket bucket --VersioningConfiguration.Status Suspended
  command:
  - api
  - PutBucketVersioning
  - --Bucket
  - '%0'
  - --VersioningConfiguration.Status
  - Suspended
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: describe bucket
  alias_to: GetBucketEncryption
  aliases:
  - desc
  short: Display encryption configuration, alias for api GetBucketEncryption --Bucket bucket
  command:
  - api
  - GetBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: encryption
  use: enable bucket
  alias_to: PutBucketEncryption
  short: Enable encryption, alias for api PutBucketEncryption --Bucket bucket --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm AES256
  command:
  - api
  - PutBucketEncryption
  - --Bucket
  - '%0'
  - --ServerSideEncryptionConfiguration.Rules.0.ApplyServerSideEncryptionByDefault.SSEAlgorithm
  - AES256
  - --output
  - success
- entity: bucket
  sub_command: encryption
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketEncryption
  short: Disable encryption, alias for api DeleteBucketEncryption --Bucket bucket
  command:
  - api
  - DeleteBucketEncryption
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: acl
  use: describe bucket
  alias_to: GetBucketAcl
  aliases:
  - desc
  short: Display ACL configuration, alias for api GetBucketAcl --Bucket bucket
  command:
  - api
  - GetBucketAcl
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: acl
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketAcl
  short: Update ACL configuration, alias for api PutBucketAcl --Bucket bucket
  command:
  - api
  - PutBucketAcl
  - --Bucket
  - '%0'
  - --template-root
  - AccessControlPolicy
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    usage: 'the file storing the ACL config in JSON format (i.e. {"Grants":[...]})'
  - name: acl
    alias_to: ACL
  - name: grant-full-control
    alias_to: GrantFullControl
  - name: grant-read
    alias_to: GrantRead
  - name: GrantReadACP
    alias_to: grant-read-acp
  - name: grant-write
    alias_to: GrantWrite
  - name: grant-write-acp
    alias_to: GrantWriteACP
- entity: bucket
  sub_command: cors
  use: describe bucket
  alias_to: GetBucketCors
  aliases:
  - desc
  short: Display CORS configuration, alias for api GetBucketCors --Bucket bucket
  command:
  - api
  - GetBucketCors
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: cors
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketCors
  short: Update CORS configuration, alias for api PutBucketCors --Bucket bucket
  command:
  - api
  - PutBucketCors
  - --Bucket
  - '%0'
  - --template-root
  - CORSConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the CORS config in JSON format (i.e. {"CORSRules":[...]})'
- entity: bucket
  sub_command: cors
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketCors
  short: Delete CORS configuration, alias for api DeleteBucketCors --Bucket bucket
  command:
  - api
  - DeleteBucketCors
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: lifecycle
  use: describe bucket
  alias_to: GetBucketLifecycleConfiguration
  aliases:
  - desc
  short: Display lifecycle configuration, alias for api GetBucketLifecycleConfiguration --Bucket bucket
  command:
  - api
  - GetBucketLifecycleConfiguration
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: lifecycle
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketLifecycleConfiguration
  short: Update Lifecycle configuration, alias for api PutBucketLifecycleConfiguration --Bucket bucket
  command:
  - api
  - PutBucketLifecycleConfiguration
  - --Bucket
  - '%0'
  - --template-root
  - LifecycleConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the Lifecycle config in JSON format (i.e. {"Rules":[...]})'
- entity: bucket
  sub_command: lifecycle
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketLifecycle
  short: Delete Lifecycle configuration, alias for api DeleteBucketLifecycle --Bucket bucket
  command:
  - api
  - DeleteBucketLifecycle
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: objectlock
  use: describe bucket
  alias_to: GetObjectLockConfiguration
  aliases:
  - desc
  short: Display ObjectLock configuration, alias for api GetObjectLockConfiguration --Bucket bucket
  command:
  - api
  - GetObjectLockConfiguration
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: objectlock
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutObjectLockConfiguration
  short: Update ObjectLock configuration, alias for api PutObjectLockConfiguration --Bucket bucket
  command:
  - api
  - PutObjectLockConfiguration
  - --Bucket
  - '%0'
  - --template-root
  - ObjectLockConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the ObjectLock config in JSON format (i.e. {"ObjectLockEnabled":"Enabled", "Rule":{...}})'
- entity: bucket
  sub_command: website
  use: describe bucket
  alias_to: GetBucketWebsite
  aliases:
  - desc
  short: Display website configuration, alias for api GetBucketWebsite --Bucket bucket
  command:
  - api
  - GetBucketWebsite
  - --Bucket
  - '%0'
  - --output
  - yaml
- entity: bucket
  sub_command: website
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketWebsite
  short: Update Website configuration, alias for api PutBucketWebsite --Bucket bucket
  command:
  - api
  - PutBucketWebsite
  - --Bucket
  - '%0'
  - --template-root
  - WebsiteConfiguration
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the website config in JSON format (e.g. {"ErrorDocument":{...},"IndexDocument":{...},"RoutingRules":[...]})'
- entity: bucket
  sub_command: website
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketWebsite
  short: Delete Website configuration, alias for api DeleteBucketWebsite --Bucket bucket
  command:
  - api
  - DeleteBucketWebsite
  - --Bucket
  - '%0'
  - --output
  - success
- entity: bucket
  sub_command: policy
  use: describe bucket
  alias_to: GetBucketPolicy
  aliases:
  - desc
  short: Display Policy configuration, alias for api GetBucketPolicy --Bucket bucket
  command:
  - api
  - GetBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - text
- entity: bucket
  sub_command: policy
  use: configure bucket
  aliases:
    - config
    - cfg
  alias_to: PutBucketPolicy
  short: Update Policy configuration, alias for api PutBucketPolicy --Bucket bucket
  command:
  - api
  - PutBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - success
  flags:
  - name: from-file
    alias_to: Policy
    type: file
    required: true
    usage: 'the file storing the policy config in JSON format (i.e. {"Version":"...","Statement":[...]})'
  - name: remove-access
    alias_to: ConfirmRemoveSelfBucketAccess
- entity: bucket
  sub_command: policy
  use: disable bucket
  aliases:
    - del
    - rm
  alias_to: DeleteBucketPolicy
  short: Delete Policy configuration, alias for api DeleteBucketPolicy --Bucket bucket
  command:
  - api
  - DeleteBucketPolicy
  - --Bucket
  - '%0'
  - --output
  - success
- entity: object
  sub_command: acl
  use: describe key
  alias_to: GetObjectAcl
  aliases:
  - desc
  short: Display ACL configuration, alias for api GetObjectAcl --Key key
  command:
  - api
  - GetObjectAcl
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: acl
  use: configure key
  alias_to: PutObjectAcl
  aliases:
  - config
  - cfg
  short: Configure ACL, alias for api PutObjectAcl --Key key
  command:
  - api
  - PutObjectAcl
  - --Key
  - '%0'
  - --template-root
  - AccessControlPolicy
  - --output
  - yaml
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the ACL config in JSON format (i.e. {"Grants":[...]})'
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: retention
  use: desc key
  alias_to: GetObjectRetention
  aliases:
  - desc
  short: Display retention configuration, alias for api GetObjectRetention --Key key
  command:
  - api
  - GetObjectRetention
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: retention
  use: configure key
  alias_to: PutObjectRetention
  aliases:
  - config
  - cfg
  short: Configure object retention, alias for api PutObjectRetention --Key key --Retention.Mode
  command:
  - api
  - PutObjectRetention
  - --Key
  - '%0'
  - --Retention.Mode
  - COMPLIANCE
  - --output
  - success
  flags:
  - name: retain-until
    alias_to: Retention.RetainUntilDate
    required: true
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: describe key
  alias_to: GetObjectTagging
  aliases:
  - desc
  short: List object tags, alias for api GetObjectTagging --Key key
  command:
  - api
  - GetObjectTagging
  - --Key
  - '%0'
  - --output
  - yaml
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: configure key
  aliases:
    - config
    - cfg
  alias_to: PutObjectTagging
  short: Add tags to an object, alias for api PutObjectTagging --Key key
  command:
  - api
  - PutObjectTagging
  - --Key
  - '%0'
  - --template-root
  - Tagging
  - --output
  - success
  flags:
  - name: from-file
    alias_to: template
    required: true
    usage: 'the file storing the tagging config in JSON format (i.e. {"TagSet":[{"Key":"...", "Value":"..."}]})'
  - name: bucket
    alias_to: Bucket
    required: true
- entity: object
  sub_command: tagging
  use: delete key
  aliases:
    - del
    - rm
  alias_to: DeleteObjectTagging
  short: Delete all tags from an object, alias for api DeleteObjectTagging --Key key
  command:
  - api
  - DeleteObjectTagging
  - --Key
  - '%0'
  - --output
  - success
  flags:
  - name: bucket
    alias_to: Bucket
    required: true
