name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⬇️ Install Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      with:
        go-version-file: 'go.mod'
    - name: 🔎 golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
      with:
        version: v2.7.1
        args: --timeout=300s
        only-new-issues: true
    - name: 📦 Build
      run: go build -o octl main.go
  unit:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⬇️ Install Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      with:
        go-version-file: 'go.mod'
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@master
      with:
        access_key: ${{ secrets.OSC_ACCESS_KEY }}
        secret_key: ${{ secrets.OSC_SECRET_KEY }}
        region: "eu-west-2"
    - name: 🧪 Test
      run: go test -v ./...
      env:
        OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
        OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        OSC_REGION: "eu-west-2"