name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@bd54158ec41d8d18182eb99e516353ed5ea92858 # v1.0.1
    - name: 📦 Build
      run: go build -o octl main.go
  unit:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@1a8eba5199913da60ae6d92d6050e17410186a38 # v0.16.1+hotfix.0
      with:
        access_key: ${{ secrets.OSC_ACCESS_KEY }}
        secret_key: ${{ secrets.OSC_SECRET_KEY }}
        region: "eu-west-2"
        providers: "outscale_oapi,outscale_oos,outscale_oks"
    - name: 🧪 Test
      run: go test -v ./... -timeout 60m
      env:
        OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
        OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        OSC_REGION: "eu-west-2"
        IMAGE_ID: ${{ vars.IMAGE_ID }}
        VM_TYPE: ${{ vars.VM_TYPE }}
