name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: ⬇️ Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@ba9b0e7bcc1ab4b8fd2c69d8b4de17d86218f5b5 # v1.0.0
    - name: 📦 Build
      run: go build -o octl main.go
  unit:
    runs-on: [self-hosted, linux, eu-west-2]
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: ⬇️ Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@373088e518c62c8fceb29e49bf6db4298da87113 # v0.15.0+hotfix.0
      with:
        access_key: ${{ secrets.OSC_ACCESS_KEY }}
        secret_key: ${{ secrets.OSC_SECRET_KEY }}
        region: "eu-west-2"
        providers: "outscale_oapi,outscale_oos,outscale_oks"
    - name: 🧪 Test
      run: go test -v ./... -timeout 60m
      env:
        OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
        OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        OSC_REGION: "eu-west-2"
        IMAGE_ID: ${{ vars.IMAGE_ID }}
        VM_TYPE: ${{ vars.VM_TYPE }}
