name: Check generated content

on:
  pull_request:
    branches:
      - main
      - docautogen

    
permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⚙️ Generate and check diff
      run: |
        set -ex
        go generate ./...
        git diff --exit-code
