name: Check generated content

on:
  pull_request:
    branches:
      - main
      - docautogen

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: ⚙️ Generate and check diff
      run: |
        set -ex
        go generate ./...
        git add .
        git diff --staged --exit-code
