name: PR comments

on:
  pull_request:
    branches:
      - main
      - docautogen


permissions:
  contents: read
#   issues: write
  pull-requests: write

jobs:
  binarysize:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: main
    - name: 📦 Run GoReleaser
      uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
      with:
        version: '~> v2'
        args: build --skip validate --clean --snapshot --single-target
      env:
        KUBECTL_VERSION: 1.2.3
    - name: ⚖️ Compute before size
      id: before
      run: |
        SZ=$(stat --format "%s" dist/*/octl)
        SZ=$(bc <<< $SZ/1024)
        echo "before: $SZ KB"
        echo "size=$SZ" >> "$GITHUB_OUTPUT"
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: 📦 Run GoReleaser
      uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
      with:
        version: '~> v2'
        args: build --skip validate --clean --snapshot --single-target
      env:
        KUBECTL_VERSION: 1.2.3
    - name: ⚖️ Compute after size
      id: after
      run: |
        SZ=$(stat --format "%s" dist/*/octl)
        SZ=$(bc <<< $SZ/1024)
        echo "after: $SZ KB"
        echo "size=$SZ" >> "$GITHUB_OUTPUT"
    - name: ⚖️ Compute diff
      id: size
      run: |
        CHANGE=$(bc <<< "$AFTER - $BEFORE")
        echo "change: $CHANGE KB"
        PERC=$(bc <<< "scale=3; ($AFTER - $BEFORE) / $BEFORE * 100")
        echo "delta: $PERC %"
        BEFORE=$(bc <<< "scale=1;$BEFORE/1024")
        AFTER=$(bc <<< "scale=1;$AFTER/1024")
        fmt=$(printf '%.1fMB => %.1fMB (change %+dKB, %+.1f%%)' $BEFORE $AFTER $CHANGE $PERC)
        if [ $CHANGE -gt 500 ]; then
          fmt="$fmt 😭"
        elif [ $CHANGE -gt 100 ]; then
          fmt="$fmt ☹️"
        elif [ $CHANGE -lt -250 ]; then
          fmt="$fmt 🤩"
        elif [ $CHANGE -lt 0 ]; then
          fmt="$fmt 😀"
        else
          fmt="$fmt 😉"
        fi
        echo "delta=$fmt" >> "$GITHUB_OUTPUT"
      env:
        BEFORE: ${{ steps.before.outputs.size }}
        AFTER: ${{ steps.after.outputs.size }}
    - name: 🔎 Find Comment
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4
      id: find
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Binary size
    - name: 📝 Create or update comment
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
      with:
        comment-id: ${{ steps.find.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **Binary size**: ${{ steps.size.outputs.delta }}
        edit-mode: replace

  generate:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
    - name: ⚖️ Diff before/after
      id: diff
      run: |
        set -ex
        git add .
        git diff --staged -w -U0 refs/remotes/origin/main -- docs/reference | egrep -v '^(@@ |index |--- |\+\+\+ )' | sed -E 's|^diff --git a/(.*) .*$|```\n\1\n```|g' | tail -n +2 | tee diff
        if [ -s diff ]; then
          echo "**WARNING : Differences in reference doc** 🤔" > diffmsg.txt
          echo '```' >> diffmsg.txt
          git diff --staged --stat  refs/remotes/origin/main -- docs/reference >> diffmsg.txt
          echo '```' >> diffmsg.txt
          echo "<details><summary>Detailed changes</summary>" >> diffmsg.txt
          echo >> diffmsg.txt
          head -200 diff >> diffmsg.txt
          if [ `cat diff|wc -l` -gt 200 ]; then
            echo "[...]" >> diffmsg.txt
          fi
          count=$(grep -c '```' diffmsg.txt)
          even=$(bc <<< "$count%2")
          if [ $even -eq 1 ]; then
            echo '```' >> diffmsg.txt
          fi
          echo "</details>" >> diffmsg.txt
        else
          echo "**No diff in reference doc** 😀" > diffmsg.txt
        fi

    - name: 🔎 Find Comment
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4
      id: find
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: reference doc
    - name: 📝 Create or update comment
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
      with:
        comment-id: ${{ steps.find.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: diffmsg.txt
        edit-mode: replace
