name: release

on:
    push:
        tags:
            - "v*"

permissions:
  contents: write
  id-token: write

jobs:
    goreleaser:
        environment: release
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Install Cosign
              uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4

            - name: ⬇️ Set up Go
              uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
              with:
                  go-version-file: "./go.mod"

            # - name: Import GPG key
            #   id: import_gpg
            #   uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6
            #   with:
            #       GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            #       PASSPHRASE: ${{ secrets.PASSPHRASE }}

            - name: 📦 Run GoReleaser
              uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
              with:
                version: '~> v2'
                args: release --clean
              env:
                #   GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}