name: release

on:
    push:
        tags:
            - "v*"

permissions:
  contents: write
  id-token: write

jobs:
    goreleaser:
        environment: release
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Install Cosign
              uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4

            - name: ⬇️ Set up Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version-file: "./go.mod"

            - name: 🧮 Compute kubectl version
              id: version
              run: |
                  minorpatch=`grep kubectl go.mod | sed 's/.*kubectl v0//'`
                  echo "KUBECTL_VERSION=1$minorpatch" >> $GITHUB_OUTPUT

            - name: 📦 Run GoReleaser
              uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
              with:
                version: '~> v2'
                args: release --clean
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                KUBECTL_VERSION: ${{ steps.version.KUBECTL_VERSION }}
